import { useGameStore } from '@/game/store/gameStore';
import { fontFamily } from '@/ui/theme';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const dayLabel=(iso:string)=>{const d=new Date(iso),today=new Date(),y=new Date();y.setDate(today.getDate()-1);if(d.toDateString()===today.toDateString())return 'Сегодня';if(d.toDateString()===y.toDateString())return 'Вчера';return d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});};
export default function HistoryScreen(){const router=useRouter();const txs=useGameStore((s)=>s.transactions);let last='';return <SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>История покупок</Text></View><ScrollView contentContainerStyle={styles.content}>{txs.length?txs.map((tx)=>{const day=dayLabel(tx.createdAt),show=day!==last;last=day;return <View key={tx.id}>{show?<Text style={styles.day}>{day}</Text>:null}<View style={styles.row}><View style={styles.icon}><Text>{tx.amount>=0?'↗':'↘'}</Text></View><View style={styles.info}><Text style={styles.name}>{tx.title}</Text><Text style={styles.time}>{new Date(tx.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={[styles.amount,tx.amount>=0?styles.plus:styles.minus]}>{tx.amount>=0?'+':''}{tx.amount} 🟡</Text></View></View>}):<View style={styles.empty}><Text style={styles.emptyTitle}>История пока пустая</Text><Text style={styles.emptyText}>Покупки в магазине, награды и операции с целями появятся здесь автоматически.</Text></View>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F5F4F2'},header:{height:58,flexDirection:'row',alignItems:'center',paddingHorizontal:18},back:{fontSize:38,width:35,color:'#2A180E'},title:{fontFamily:fontFamily.bold,fontSize:20,color:'#2A180E'},content:{padding:18,paddingBottom:40},day:{fontFamily:fontFamily.bold,fontSize:15,color:'#302018',marginTop:14,marginBottom:8},row:{minHeight:70,borderRadius:12,backgroundColor:'#fff',padding:11,flexDirection:'row',alignItems:'center',marginBottom:8,borderWidth:1,borderColor:'#E3DFDC'},icon:{width:42,height:42,borderRadius:21,backgroundColor:'#F0ECE9',alignItems:'center',justifyContent:'center'},info:{flex:1,paddingHorizontal:10},name:{fontFamily:fontFamily.semiBold,color:'#2B1C13',fontSize:13},time:{fontFamily:fontFamily.medium,color:'#8A7F78',fontSize:10,marginTop:4},amount:{fontFamily:fontFamily.bold,fontSize:13},plus:{color:'#3B7925'},minus:{color:'#A14432'},empty:{alignItems:'center',paddingTop:180,paddingHorizontal:24},emptyTitle:{fontFamily:fontFamily.bold,fontSize:20,color:'#2A1B12'},emptyText:{fontFamily:fontFamily.medium,color:'#7A6F68',lineHeight:19,textAlign:'center',marginTop:8}});
