import { CHAPTERS } from '@/features/learning/content';
import { useGameStore } from '@/game/store/gameStore';
import { useProfileStore } from '@/store/profileStore';
import { fontFamily } from '@/ui/theme';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
export default function ParentScreen(){const router=useRouter();const player=useProfileStore((s)=>s.playerName);const pet=useProfileStore((s)=>s.petName);const done=useGameStore((s)=>s.completedLessons);const accuracy=useGameStore((s)=>s.lessonAccuracy);const goals=useGameStore((s)=>s.goals);const avg=done.length?Math.round(done.reduce((s,id)=>s+(accuracy[id]??0),0)/done.length):0;return <SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Раздел для взрослого</Text></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.lead}>{player||'Игрок'} и {pet||'Финни'}</Text><View style={styles.stats}><Box n={`${done.length}/12`} t="уроков"/><Box n={`${avg}%`} t="точность"/><Box n={`${goals.filter(g=>!g.purchasedAt).length}`} t="активных целей"/></View><Text style={styles.h2}>По главам</Text>{CHAPTERS.map((c)=><View key={c.id} style={styles.row}><View style={[styles.dot,{backgroundColor:c.color}]}/><Text style={styles.rowName}>{c.title}</Text><Text style={styles.rowValue}>{c.lessons.filter(x=>done.includes(x)).length}/4</Text></View>)}<Text style={styles.note}>Finny не подключается к банковским счетам. Все монеты, цели и операции внутри приложения учебные и хранятся локально на устройстве.</Text></ScrollView></SafeAreaView>}
function Box({n,t}:{n:string;t:string}){return <View style={styles.box}><Text style={styles.boxN}>{n}</Text><Text style={styles.boxT}>{t}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F5F4F2'},header:{height:58,flexDirection:'row',alignItems:'center',paddingHorizontal:18},back:{fontSize:38,width:35,color:'#2A180E'},title:{fontFamily:fontFamily.bold,fontSize:20,color:'#2A180E'},content:{padding:18},lead:{fontFamily:fontFamily.bold,fontSize:24,color:'#2A180E',marginBottom:15},stats:{flexDirection:'row',gap:8},box:{flex:1,minHeight:88,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',padding:8},boxN:{fontFamily:fontFamily.bold,fontSize:19,color:'#2A180E'},boxT:{fontFamily:fontFamily.medium,fontSize:10,color:'#776A63',textAlign:'center',marginTop:4},h2:{fontFamily:fontFamily.bold,fontSize:18,color:'#2A180E',marginTop:24,marginBottom:9},row:{height:60,borderRadius:12,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',padding:10,marginBottom:7},dot:{width:34,height:34,borderRadius:17},rowName:{flex:1,fontFamily:fontFamily.semiBold,color:'#2A180E',paddingHorizontal:10},rowValue:{fontFamily:fontFamily.bold,color:'#655044'},note:{fontFamily:fontFamily.medium,fontSize:11,lineHeight:17,color:'#7D716A',marginTop:22}});
